### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by endel** [ravingupta/brainyquote#2]
I was trying to run this locally, and got this error. Using `python2.7`.

Scanning URL: http://www.brainyquote.com/authors/zsa_zsa_gabor
Scanning URL: http://www.brainyquote.com/authors/zubin_mehta
Scanning URL: http://www.brainyquote.com/authors/zuleikha_robinson
Scanning URL: http://www.brainyquote.com/authors/zygmunt_bauman

Scanning Started for fetching quotes

```
Traceback (most recent call last):
  File "quotes.py", line 100, in <module>
    get_authors()
  File "quotes.py", line 58, in get_authors
    quote_details = fetch_quote(url)
  File "quotes.py", line 77, in fetch_quote
    tempString += ("\"%s\","%next(q.find_class('b-qt')[0].iter('a')).text)
IndexError: list index out of range
```

**Comment by PopeDollar** [comment]
hey bro! I have the same issue :( what's the fix for "IndexError: list index out of range" ? thank you!
